import {
  collection, getDocs, addDoc, updateDoc, getDoc, doc, query,
  where, orderBy, serverTimestamp, Timestamp, increment, arrayUnion,
} from 'firebase/firestore'
import { db } from './firebase'
import { CLASS_STATUS, PAYROLL_STATUS } from '../utils/constants'
import { getPeriodStart, getPeriodEnd, getPeriodLabel } from '../utils/dateHelpers'
import { logExpenseFromPayroll } from './cashflow.service'

/**
 * Determine quincena period for a date.
 * Q1 = days 1-15, Q2 = days 16-end of month
 */
export function periodForDate(date) {
  const d = date instanceof Date ? date : (date?.toDate ? date.toDate() : new Date(date))
  const day = d.getDate()
  const quincena = day <= 15 ? 'Q1' : 'Q2'
  const monthKey = `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}`
  const period = `${monthKey}-${quincena}`
  const startDate = quincena === 'Q1'
    ? new Date(d.getFullYear(), d.getMonth(), 1, 0, 0, 0)
    : new Date(d.getFullYear(), d.getMonth(), 16, 0, 0, 0)
  const endDate = quincena === 'Q1'
    ? new Date(d.getFullYear(), d.getMonth(), 15, 23, 59, 59)
    : new Date(d.getFullYear(), d.getMonth() + 1, 0, 23, 59, 59)
  return { period, quincena, monthKey, startDate, endDate }
}

/**
 * Auto-add a class to the coach's payroll for its period (idempotent by classId).
 */
export async function addClassToPayroll(cls, coach) {
  if (!cls?.coachId || !cls?.id) return
  const { period, quincena, monthKey, startDate, endDate } = periodForDate(cls.scheduledDate)
  const durationHours = (cls.durationMinutes || 60) / 60
  const studentsAttended = (cls.attendeeList || []).filter((a) => a.checkedIn).length
  const hourlyRate = coach?.hourlyRate || 0
  const earned = durationHours * hourlyRate

  const q = query(
    collection(db, 'payroll'),
    where('coachId', '==', cls.coachId),
    where('period', '==', period)
  )
  const snap = await getDocs(q)

  const classDetail = {
    classId: cls.id,
    className: cls.name,
    classDate: cls.scheduledDate,
    durationHours,
    studentsAttended,
    earned,
  }

  if (snap.empty) {
    await addDoc(collection(db, 'payroll'), {
      coachId: cls.coachId,
      coachName: cls.coachName || coach?.displayName,
      period,
      quincena,
      monthKey,
      startDate: Timestamp.fromDate(startDate),
      endDate: Timestamp.fromDate(endDate),
      hoursWorked: durationHours,
      classesGiven: 1,
      hourlyRate,
      totalEarned: earned,
      runningTotal: earned,
      classDetails: [classDetail],
      status: PAYROLL_STATUS.DRAFT,
      autoGenerated: true,
      lastClassAddedAt: serverTimestamp(),
      createdAt: serverTimestamp(),
      updatedAt: serverTimestamp(),
    })
  } else {
    const docRef = snap.docs[0].ref
    const data = snap.docs[0].data()
    if ((data.classDetails || []).some((c) => c.classId === cls.id)) return // already added
    await updateDoc(docRef, {
      hoursWorked: increment(durationHours),
      classesGiven: increment(1),
      totalEarned: increment(earned),
      runningTotal: increment(earned),
      classDetails: arrayUnion(classDetail),
      lastClassAddedAt: serverTimestamp(),
      updatedAt: serverTimestamp(),
    })
  }
}

/**
 * Get all payroll docs for a specific period.
 */
export async function getPayrollByPeriod(period) {
  const q = query(collection(db, 'payroll'), where('period', '==', period))
  const snap = await getDocs(q)
  return snap.docs.map((d) => ({ id: d.id, ...d.data() }))
}

/**
 * Get current period payroll for all coaches.
 */
export async function getCurrentPayrollPeriod() {
  const { period } = periodForDate(new Date())
  return getPayrollByPeriod(period)
}

/**
 * Approve and pay payroll — creates auto cashflow expense.
 */
export async function approveAndPayPayroll(payrollId, adminUid, paymentNotes) {
  const payRef = doc(db, 'payroll', payrollId)
  const snap = await getDoc(payRef)
  if (!snap.exists()) throw new Error('Nómina no encontrada')
  const data = snap.data()

  await updateDoc(payRef, {
    status: PAYROLL_STATUS.PAID,
    approvedBy: adminUid,
    approvedAt: serverTimestamp(),
    paidAt: serverTimestamp(),
    paymentNotes: paymentNotes || '',
    updatedAt: serverTimestamp(),
  })

  await logExpenseFromPayroll({
    payrollId,
    amount: data.totalEarned || 0,
    description: `Nómina ${data.coachName} — ${data.period}`,
    adminUid,
  })
}

export async function generatePayroll(coachId, coachName, hourlyRate, period) {
  const start = getPeriodStart(period)
  const end = getPeriodEnd(period)

  const q = query(
    collection(db, 'classes'),
    where('coachId', '==', coachId),
    where('scheduledDate', '>=', Timestamp.fromDate(start)),
    where('scheduledDate', '<=', Timestamp.fromDate(end)),
    where('status', '==', CLASS_STATUS.COMPLETED)
  )
  const snaps = await getDocs(q)
  const classes = snaps.docs.map((d) => ({ id: d.id, ...d.data() }))

  const classDetails = classes.map((cls) => {
    const durationHours = (cls.durationMinutes || 60) / 60
    const earned = durationHours * hourlyRate
    return {
      classId: cls.id,
      className: cls.name,
      classDate: cls.scheduledDate,
      durationHours,
      studentsAttended: cls.attendedCount || 0,
      earned,
    }
  })

  const hoursWorked = classDetails.reduce((acc, c) => acc + c.durationHours, 0)
  const totalEarned = classDetails.reduce((acc, c) => acc + c.earned, 0)

  const ref = await addDoc(collection(db, 'payroll'), {
    coachId,
    coachName,
    period,
    startDate: Timestamp.fromDate(start),
    endDate: Timestamp.fromDate(end),
    hoursWorked,
    classesGiven: classes.length,
    hourlyRate,
    totalEarned,
    classDetails,
    status: PAYROLL_STATUS.DRAFT,
    approvedBy: null,
    approvedAt: null,
    paidAt: null,
    paymentNotes: '',
    createdAt: serverTimestamp(),
    updatedAt: serverTimestamp(),
  })
  return ref.id
}

export async function getCoachPayrolls(coachId) {
  const q = query(
    collection(db, 'payroll'),
    where('coachId', '==', coachId),
    orderBy('period', 'desc')
  )
  const snaps = await getDocs(q)
  return snaps.docs.map((d) => ({ id: d.id, ...d.data() }))
}

export async function getAllPayrolls() {
  const q = query(collection(db, 'payroll'), orderBy('period', 'desc'))
  const snaps = await getDocs(q)
  return snaps.docs.map((d) => ({ id: d.id, ...d.data() }))
}

export async function approvePayroll(payrollId, adminId) {
  await updateDoc(doc(db, 'payroll', payrollId), {
    status: PAYROLL_STATUS.APPROVED,
    approvedBy: adminId,
    approvedAt: serverTimestamp(),
    updatedAt: serverTimestamp(),
  })
}

export async function markPayrollPaid(payrollId, notes = '') {
  await updateDoc(doc(db, 'payroll', payrollId), {
    status: PAYROLL_STATUS.PAID,
    paidAt: serverTimestamp(),
    paymentNotes: notes,
    updatedAt: serverTimestamp(),
  })
}
